services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: Leakops-backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"
    volumes:
      - leakops_pgdata:/var/lib/postgresql/data

volumes:
  leakops_pgdata:

